export default {
  SUMMARY_FETCH_REQUEST: 'SUMMARY_FETCH_REQUEST',
  SUMMARY_FETCH_SUCCESS: 'SUMMARY_FETCH_SUCCESS',
  DAILY_FETCH_REQUEST: 'DAILY_FETCH_REQUEST',
  DAILY_FETCH_SUCCESS: 'DAILY_FETCH_SUCCESS',
  PLACES_FETCH_REQUEST: 'PLACES_FETCH_REQUEST',
  PLACES_FETCH_SUCCESS: 'PLACES_FETCH_SUCCESS',
}
