export default {
  SUMMARY_FETCH_REQUEST: 'SUMMARY_FETCH_REQUEST',
  SUMMARY_FETCH_SUCCESS: 'SUMMARY_FETCH_SUCCESS',
  SUMMARY_FETCH_DAILY_REQUEST: 'SUMMARY_FETCH_DAILY_REQUEST',
  SUMMARY_FETCH_DAILY_SUCCESS: 'SUMMARY_FETCH_DAILY_SUCCESS',
}
